name: flutter_complete_guide
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_svg: ^0.19.0
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  camera: ^0.5.7+4
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0+1
  firebase_storage:
  google_fonts:
  sticky_grouped_list: ^1.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  #assets:
  assets:
    - images/calculator.jpg
    - images/camera.png
    - images/list.png
    - images/more.png
    - images/picture1.png
    - images/bg.png
    - assets/images/
    - assets/icons/
    - assets/asset/scan.png
    - assets/asset/list.png
    - assets/asset/cal.png
    - assets/asset/bmi.png
    - assets/asset/his.png
    - assets/asset/settings.png
    - images/grain-sack.png
    - images/dairy-products.png
    - images/canned-food.png
    - images/chocolate.png
    - images/drink.png
    - images/snacks.png
    - images/thanksgiving.png
    - images/breakfast.png
    - images/bakery.png
    - images/wlcome.png
    - images/welcom.png
    - images/hii.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
